language: node_js
node_js:
- 11
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run lint
- yarn run generate
before_install:
- openssl aes-256-cbc -K $encrypted_652f2aa5a98a_key -iv $encrypted_652f2aa5a98a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
